use_default_settings: true

server:
  secret_key: "zrsgpniaemlxb1k058f3d726ovhqwytc"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

outgoing:
  request_timeout: 8.0
  max_request_timeout: 15.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: wikidata
    engine: wikidata
    shortcut: wd
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    disabled: false

  - name: npm
    engine: npm
    shortcut: npm
    disabled: false
